### ISSUE TITLE
Некорректная отправка картинки

### ISSUE THREAD

**Issue by AndreyKaluzhin** [green-api/green-api-postman-collection#2]
Используя метод sendFileByUpload с помощью Python отправляю файл с расширением *.jpg
Если отправляю из POSTMAN всё нормально (первая картинка)
Если отправляю с локального компьютера из Python, получается не так как требуется. Файл нужно скачивать и просматривать, а это не то, что нужно. В чём может быть проблема?
![image](https://user-images.githubusercontent.com/93865218/174113423-adbb5106-4cc4-4474-ab5d-2872526781fa.png)

**Comment by Slikman1** [comment]
Требуется явно указывать content-type при отправке, в этом случае будет image/jpeg
