### ISSUE TITLE
Postman do not recongnize your collection files

### ISSUE THREAD

**Issue by finintra** [green-api/green-api-postman-collection#7]
Have tried both en and russian
Please see the screenshot: https://prnt.sc/g4soUVg864gY

**Comment by finintra** [comment]
Hovever the file from SW-1515 worked

**Comment by EscHelpNew** [comment]
Everything works, check out the video tutorial on how to work with the collection https://youtu.be/MkuiIck5Z4c or make a more detailed description of the problem, thanks
